import type { Language } from '@/types';

export const gcode = {
  slug: 'gcode',
  publishedDate: '1958-01-01',
  extensions: ['.gcode', '.gco', '.nc', '.cnc', '.tap'],
  author: 'MIT Servomechanisms Laboratory',
  website: 'https://www.nist.gov/publications/nist-rs274ngc-interpreter-version-3',
  paradigms: ['machine control', 'imperative'],
  tooling: {
    runtimes: ['CNC controllers', '3D printer firmware'],
    ecosystems: ['CNC machining', 'Additive manufacturing'],
  },
  version: 'RS-274',
  logo: 'https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_gcode.svg',
  color: '#DC2626',
  i18n: {
    en: {
      name: 'G-code',
      description:
        'A machine-control language for CNC tools, mills, lathes, routers, and 3D printers.',
      longDescription:
        'G-code is a family of machine-control languages used to command motion, speed, coordinates, tools, temperatures, and other manufacturing operations. Programs are usually generated by CAM or slicer software, then interpreted by machine controllers.\n\nIt is common in CNC machining, laser cutting, routing, milling, turning, and additive manufacturing. Dialects vary by controller and vendor, so practical G-code often depends on a specific machine profile.',
    },
    es: {
      name: 'G-code',
      description:
        'Lenguaje de control de maquinas para CNC, fresadoras, tornos, routers e impresoras 3D.',
      longDescription:
        'G-code es una familia de lenguajes de control de maquinas usada para ordenar movimiento, velocidad, coordenadas, herramientas, temperaturas y otras operaciones de fabricacion. Los programas suelen generarse con software CAM o slicers y luego los interpretan controladores de maquina.\n\nEs comun en mecanizado CNC, corte laser, routing, fresado, torneado y fabricacion aditiva. Los dialectos varian por controlador y proveedor, asi que el G-code practico suele depender de un perfil de maquina especifico.',
    },
    it: {
      name: 'G-code',
      description:
        'Linguaggio di controllo macchina per utensili CNC, frese, torni, router e stampanti 3D.',
      longDescription:
        'G-code e una famiglia di linguaggi di controllo macchina usata per comandare movimento, velocita, coordinate, utensili, temperature e altre operazioni di produzione. I programmi sono di solito generati da software CAM o slicer e poi interpretati dai controller.\n\nE comune in lavorazione CNC, taglio laser, routing, fresatura, tornitura e produzione additiva. I dialetti variano per controller e fornitore, quindi il G-code pratico dipende spesso da un profilo macchina specifico.',
    },
    fr: {
      name: 'G-code',
      description:
        'Langage de controle machine pour outils CNC, fraiseuses, tours, routeurs et imprimantes 3D.',
      longDescription:
        'G-code est une famille de langages de controle machine pour commander mouvement, vitesse, coordonnees, outils, temperatures et autres operations de fabrication. Les programmes sont souvent generes par logiciel CAM ou slicer, puis interpretes par des controleurs.\n\nIl est courant en usinage CNC, decoupe laser, routage, fraisage, tournage et fabrication additive. Les dialectes varient selon controleur et fournisseur, donc le G-code pratique depend souvent d un profil machine precis.',
    },
    de: {
      name: 'G-code',
      description:
        'Maschinensteuerungssprache fur CNC-Werkzeuge, Frasen, Drehbanken, Router und 3D-Drucker.',
      longDescription:
        'G-code ist eine Familie von Maschinensteuerungssprachen fur Bewegung, Geschwindigkeit, Koordinaten, Werkzeuge, Temperaturen und andere Fertigungsablaufe. Programme werden meist von CAM- oder Slicer-Software erzeugt und dann von Maschinensteuerungen interpretiert.\n\nEr ist verbreitet in CNC-Bearbeitung, Laserschneiden, Routing, Frasen, Drehen und additiver Fertigung. Dialekte unterscheiden sich nach Steuerung und Anbieter, daher hangt praktischer G-code oft von einem konkreten Maschinenprofil ab.',
    },
    pt: {
      name: 'G-code',
      description:
        'Linguagem de controle de maquinas para CNC, fresadoras, tornos, routers e impressoras 3D.',
      longDescription:
        'G-code e uma familia de linguagens de controle de maquinas usada para comandar movimento, velocidade, coordenadas, ferramentas, temperaturas e outras operacoes de fabricacao. Programas geralmente sao gerados por software CAM ou slicers e depois interpretados por controladores.\n\nEle e comum em usinagem CNC, corte a laser, roteamento, fresamento, torneamento e manufatura aditiva. Dialetos variam por controlador e fornecedor, entao G-code pratico costuma depender de um perfil de maquina especifico.',
    },
  },
} satisfies Language;
