import type { Language } from "./types";

export interface LanguageIndexEntry {
  slug: string;
  extensions: readonly string[];
}

/** Lightweight slug and extension index used by lazy filename detection. */
export const languageIndex = [
  { slug: "abap", extensions: [".abap"] },
  { slug: "actionscript", extensions: [".as"] },
  { slug: "ada", extensions: [".adb", ".ads", ".ada"] },
  { slug: "agda", extensions: [".agda", ".lagda", ".lagda.md", ".lagda.rst", ".lagda.tex"] },
  { slug: "antlr", extensions: [".g4"] },
  { slug: "apex", extensions: [".cls", ".trigger"] },
  { slug: "apl", extensions: [".apl", ".dyalog"] },
  { slug: "applescript", extensions: [".applescript", ".scpt", ".scptd"] },
  { slug: "arduino", extensions: [".ino", ".pde"] },
  { slug: "asciidoc", extensions: [".adoc", ".asciidoc", ".asc"] },
  { slug: "asp", extensions: [".asp", ".aspx", ".ascx", ".ashx", ".asmx", ".master"] },
  { slug: "astro", extensions: [".astro"] },
  { slug: "assembly", extensions: [".asm", ".s", ".S", ".inc"] },
  { slug: "awk", extensions: [".awk"] },
  { slug: "autohotkey", extensions: [".ahk", ".ah2"] },
  {
    slug: "bash",
    extensions: [".sh", ".bash", ".bashrc", ".bash_profile", ".bash_login", ".profile"],
  },
  { slug: "batch", extensions: [".bat", ".cmd"] },
  {
    slug: "bazel",
    extensions: ["BUILD.bazel", "WORKSPACE", "WORKSPACE.bazel", "MODULE.bazel"],
  },
  { slug: "bicep", extensions: [".bicep", ".bicepparam"] },
  { slug: "blade", extensions: [".blade.php"] },
  { slug: "c", extensions: [".c", ".h"] },
  { slug: "carbon", extensions: [".carbon"] },
  { slug: "chapel", extensions: [".chpl"] },
  { slug: "circom", extensions: [".circom"] },
  { slug: "cmake", extensions: ["CMakeLists.txt", ".cmake"] },
  { slug: "clojure", extensions: [".clj", ".cljs", ".cljc", ".edn", ".bb"] },
  { slug: "coffeescript", extensions: [".coffee", ".litcoffee", ".cson"] },
  { slug: "coldfusion", extensions: [".cfm", ".cfml", ".cfc"] },
  { slug: "cobol", extensions: [".cob", ".cbl", ".cobol", ".cpy"] },
  { slug: "coq", extensions: [".v"] },
  { slug: "cpp", extensions: [".cpp", ".cc", ".cxx", ".h", ".hpp", ".hh", ".hxx"] },
  { slug: "csharp", extensions: [".cs", ".csx"] },
  { slug: "crystal", extensions: [".cr"] },
  { slug: "css", extensions: [".css"] },
  { slug: "cue", extensions: [".cue"] },
  { slug: "cuda", extensions: [".cu", ".cuh"] },
  { slug: "cython", extensions: [".pyx", ".pxd", ".pxi"] },
  { slug: "d", extensions: [".d", ".di"] },
  { slug: "dart", extensions: [".dart"] },
  { slug: "dhall", extensions: [".dhall"] },
  { slug: "dita", extensions: [".dita", ".ditamap", ".ditaval"] },
  { slug: "dockerfile", extensions: ["Dockerfile", ".dockerfile"] },
  { slug: "earthly", extensions: ["Earthfile"] },
  { slug: "elixir", extensions: [".ex", ".exs", ".eex", ".leex", ".heex"] },
  { slug: "elm", extensions: [".elm"] },
  { slug: "erb", extensions: [".erb", ".rhtml", ".html.erb"] },
  {
    slug: "erlang",
    extensions: [".erl", ".hrl", ".app.src", ".escript", ".xrl", ".yrl", "rebar.config"],
  },
  { slug: "fennel", extensions: [".fnl"] },
  {
    slug: "fortran",
    extensions: [".f", ".for", ".ftn", ".f90", ".f95", ".f03", ".f08", ".f18", ".f23"],
  },
  { slug: "forth", extensions: [".fs", ".fth", ".forth", ".4th"] },
  { slug: "fsharp", extensions: [".fs", ".fsi", ".fsx", ".fsscript"] },
  { slug: "gdscript", extensions: [".gd"] },
  { slug: "git", extensions: [".git", ".gitignore", ".gitattributes", ".gitmodules", ".gitkeep"] },
  { slug: "gleam", extensions: [".gleam"] },
  { slug: "go", extensions: [".go"] },
  { slug: "gradle", extensions: [".gradle", ".gradle.kts"] },
  {
    slug: "glsl",
    extensions: [".glsl", ".vert", ".frag", ".geom", ".tesc", ".tese", ".comp", ".vs", ".fs"],
  },
  { slug: "graphql", extensions: [".graphql", ".gql", ".graphqls"] },
  { slug: "groovy", extensions: [".groovy", ".gvy", ".gy", ".gsh"] },
  { slug: "handlebars", extensions: [".hbs", ".handlebars"] },
  { slug: "hack", extensions: [".hack", ".hh", ".hhi"] },
  { slug: "haml", extensions: [".haml"] },
  { slug: "haskell", extensions: [".hs", ".lhs", ".hsc", ".hs-boot", ".hsig", ".cabal"] },
  { slug: "haxe", extensions: [".hx", ".hxml"] },
  { slug: "hcl", extensions: [".hcl", ".tf", ".tfvars", ".pkr.hcl", ".nomad"] },
  { slug: "hlsl", extensions: [".hlsl", ".fx", ".fxh", ".hlsli"] },
  { slug: "html", extensions: [".html", ".htm"] },
  { slug: "idris", extensions: [".idr", ".lidr", ".ipkg"] },
  { slug: "ini", extensions: [".ini"] },
  { slug: "java", extensions: [".java"] },
  { slug: "javascript", extensions: [".js", ".mjs", ".cjs", ".jsx"] },
  { slug: "janet", extensions: [".janet", ".jdn"] },
  { slug: "jinja", extensions: [".jinja", ".jinja2", ".j2"] },
  { slug: "json", extensions: [".json"] },
  { slug: "jsonnet", extensions: [".jsonnet", ".libsonnet"] },
  { slug: "jupyter-notebook", extensions: [".ipynb"] },
  { slug: "julia", extensions: [".jl"] },
  { slug: "kotlin", extensions: [".kt", ".kts"] },
  { slug: "lean", extensions: [".lean"] },
  { slug: "less", extensions: [".less"] },
  { slug: "liquid", extensions: [".liquid"] },
  { slug: "lisp", extensions: [".lisp", ".lsp", ".cl", ".asd"] },
  { slug: "llvm-ir", extensions: [".ll", ".bc"] },
  { slug: "lua", extensions: [".lua", ".rockspec"] },
  { slug: "luau", extensions: [".luau"] },
  { slug: "makefile", extensions: ["Makefile", "makefile", "GNUmakefile", ".mk", ".mak"] },
  { slug: "matlab", extensions: [".m", ".mlx"] },
  { slug: "markdown", extensions: [".md", ".markdown", ".mdown", ".mkd"] },
  { slug: "mdx", extensions: [".mdx"] },
  { slug: "mermaid", extensions: [".mmd", ".mermaid"] },
  { slug: "meson", extensions: ["meson.build", "meson_options.txt", "meson.options", ".wrap"] },
  { slug: "metal", extensions: [".metal"] },
  { slug: "svn", extensions: [".svn", "svnserve.conf"] },
  { slug: "nginx", extensions: ["nginx.conf", ".nginx", ".conf"] },
  { slug: "nim", extensions: [".nim", ".nims", ".nimble"] },
  { slug: "nix", extensions: [".nix"] },
  { slug: "ocaml", extensions: [".ml", ".mli", ".mll", ".mly", ".mlt", ".eliom", ".eliomi"] },
  { slug: "objective-c", extensions: [".m", ".mm"] },
  { slug: "pascal", extensions: [".pas", ".pp", ".inc", ".lpr", ".dpr", ".dfm"] },
  { slug: "perl", extensions: [".pl", ".pm", ".pod", ".t", ".psgi"] },
  { slug: "php", extensions: [".php", ".phtml", ".php3", ".php4", ".php5", ".phps"] },
  { slug: "plantuml", extensions: [".puml", ".plantuml", ".iuml"] },
  { slug: "powershell", extensions: [".ps1", ".psm1", ".psd1", ".ps1xml"] },
  { slug: "prolog", extensions: [".pl", ".pro", ".prolog", ".P"] },
  { slug: "protobuf", extensions: [".proto"] },
  { slug: "pug", extensions: [".pug", ".jade"] },
  { slug: "python", extensions: [".py", ".pyw"] },
  { slug: "qml", extensions: [".qml", ".qmltypes", ".qmlproject"] },
  { slug: "r", extensions: [".r", ".R", ".rmd", ".Rmd", ".qmd", ".Rprofile"] },
  { slug: "racket", extensions: [".rkt", ".rktd", ".rktl", ".scrbl"] },
  { slug: "razor", extensions: [".cshtml", ".razor"] },
  { slug: "rego", extensions: [".rego"] },
  {
    slug: "ruby",
    extensions: [".rb", ".rbw", ".rake", ".gemspec", "Gemfile", "Rakefile", "config.ru"],
  },
  { slug: "rust", extensions: [".rs"] },
  { slug: "scala", extensions: [".scala", ".sc"] },
  { slug: "scss", extensions: [".scss", ".sass"] },
  { slug: "solidity", extensions: [".sol"] },
  { slug: "sql", extensions: [".sql"] },
  { slug: "starlark", extensions: [".bzl", ".star", ".sky"] },
  { slug: "svg", extensions: [".svg", ".svgz"] },
  { slug: "svelte", extensions: [".svelte"] },
  { slug: "swift", extensions: [".swift"] },
  { slug: "tcl", extensions: [".tcl", ".tm", ".test"] },
  { slug: "tex", extensions: [".tex", ".sty", ".cls", ".dtx", ".ins", ".ltx"] },
  { slug: "toml", extensions: [".toml"] },
  { slug: "twig", extensions: [".twig"] },
  { slug: "typescript", extensions: [".ts", ".tsx", ".mts", ".cts"] },
  { slug: "typst", extensions: [".typ"] },
  { slug: "verilog", extensions: [".v", ".vh", ".sv", ".svh"] },
  { slug: "vhdl", extensions: [".vhd", ".vhdl"] },
  { slug: "visual-basic", extensions: [".vb"] },
  { slug: "vue", extensions: [".vue"] },
  { slug: "webassembly", extensions: [".wasm", ".wat"] },
  { slug: "wgsl", extensions: [".wgsl"] },
  { slug: "xaml", extensions: [".xaml", ".baml"] },
  { slug: "xml", extensions: [".xml", ".xsd", ".xsl", ".xslt"] },
  { slug: "xquery", extensions: [".xq", ".xql", ".xqm", ".xquery", ".xqy"] },
  { slug: "xslt", extensions: [".xsl", ".xslt"] },
  { slug: "yaml", extensions: [".yaml", ".yml"] },
  { slug: "zig", extensions: [".zig", ".zon"] },
  {
    slug: "zsh",
    extensions: [".zsh", ".zshrc", ".zshenv", ".zprofile", ".zlogin", ".zlogout", ".zsh-theme"],
  },
] as const satisfies readonly LanguageIndexEntry[];

/** Explicit dynamic import map for every language module. */
export const languageLoaders = {
  abap: () => import("./languages/abap").then((module) => module.abap),
  actionscript: () => import("./languages/actionscript").then((module) => module.actionscript),
  ada: () => import("./languages/ada").then((module) => module.ada),
  agda: () => import("./languages/agda").then((module) => module.agda),
  antlr: () => import("./languages/antlr").then((module) => module.antlr),
  apex: () => import("./languages/apex").then((module) => module.apex),
  apl: () => import("./languages/apl").then((module) => module.apl),
  applescript: () => import("./languages/applescript").then((module) => module.applescript),
  arduino: () => import("./languages/arduino").then((module) => module.arduino),
  asciidoc: () => import("./languages/asciidoc").then((module) => module.asciidoc),
  asp: () => import("./languages/asp").then((module) => module.asp),
  assembly: () => import("./languages/assembly").then((module) => module.assembly),
  astro: () => import("./languages/astro").then((module) => module.astro),
  autohotkey: () => import("./languages/autohotkey").then((module) => module.autohotkey),
  awk: () => import("./languages/awk").then((module) => module.awk),
  bash: () => import("./languages/bash").then((module) => module.bash),
  batch: () => import("./languages/batch").then((module) => module.batch),
  bazel: () => import("./languages/bazel").then((module) => module.bazel),
  bicep: () => import("./languages/bicep").then((module) => module.bicep),
  blade: () => import("./languages/blade").then((module) => module.blade),
  c: () => import("./languages/c").then((module) => module.c),
  carbon: () => import("./languages/carbon").then((module) => module.carbon),
  chapel: () => import("./languages/chapel").then((module) => module.chapel),
  circom: () => import("./languages/circom").then((module) => module.circom),
  cmake: () => import("./languages/cmake").then((module) => module.cmake),
  clojure: () => import("./languages/clojure").then((module) => module.clojure),
  cobol: () => import("./languages/cobol").then((module) => module.cobol),
  coffeescript: () => import("./languages/coffeescript").then((module) => module.coffeescript),
  coldfusion: () => import("./languages/coldfusion").then((module) => module.coldfusion),
  coq: () => import("./languages/coq").then((module) => module.coq),
  cpp: () => import("./languages/cpp").then((module) => module.cpp),
  csharp: () => import("./languages/csharp").then((module) => module.csharp),
  crystal: () => import("./languages/crystal").then((module) => module.crystal),
  css: () => import("./languages/css").then((module) => module.css),
  cue: () => import("./languages/cue").then((module) => module.cue),
  cuda: () => import("./languages/cuda").then((module) => module.cuda),
  cython: () => import("./languages/cython").then((module) => module.cython),
  d: () => import("./languages/d").then((module) => module.d),
  dart: () => import("./languages/dart").then((module) => module.dart),
  dhall: () => import("./languages/dhall").then((module) => module.dhall),
  dita: () => import("./languages/dita").then((module) => module.dita),
  dockerfile: () => import("./languages/dockerfile").then((module) => module.dockerfile),
  earthly: () => import("./languages/earthly").then((module) => module.earthly),
  elixir: () => import("./languages/elixir").then((module) => module.elixir),
  elm: () => import("./languages/elm").then((module) => module.elm),
  erb: () => import("./languages/erb").then((module) => module.erb),
  erlang: () => import("./languages/erlang").then((module) => module.erlang),
  fennel: () => import("./languages/fennel").then((module) => module.fennel),
  fortran: () => import("./languages/fortran").then((module) => module.fortran),
  forth: () => import("./languages/forth").then((module) => module.forth),
  fsharp: () => import("./languages/fsharp").then((module) => module.fsharp),
  gdscript: () => import("./languages/gdscript").then((module) => module.gdscript),
  git: () => import("./languages/git").then((module) => module.git),
  gleam: () => import("./languages/gleam").then((module) => module.gleam),
  go: () => import("./languages/go").then((module) => module.go),
  gradle: () => import("./languages/gradle").then((module) => module.gradle),
  glsl: () => import("./languages/glsl").then((module) => module.glsl),
  graphql: () => import("./languages/graphql").then((module) => module.graphql),
  groovy: () => import("./languages/groovy").then((module) => module.groovy),
  handlebars: () => import("./languages/handlebars").then((module) => module.handlebars),
  hack: () => import("./languages/hack").then((module) => module.hack),
  haml: () => import("./languages/haml").then((module) => module.haml),
  haskell: () => import("./languages/haskell").then((module) => module.haskell),
  haxe: () => import("./languages/haxe").then((module) => module.haxe),
  hcl: () => import("./languages/hcl").then((module) => module.hcl),
  hlsl: () => import("./languages/hlsl").then((module) => module.hlsl),
  html: () => import("./languages/html").then((module) => module.html),
  idris: () => import("./languages/idris").then((module) => module.idris),
  ini: () => import("./languages/ini").then((module) => module.ini),
  java: () => import("./languages/java").then((module) => module.java),
  javascript: () => import("./languages/javascript").then((module) => module.javascript),
  janet: () => import("./languages/janet").then((module) => module.janet),
  jinja: () => import("./languages/jinja").then((module) => module.jinja),
  json: () => import("./languages/json").then((module) => module.json),
  jsonnet: () => import("./languages/jsonnet").then((module) => module.jsonnet),
  "jupyter-notebook": () =>
    import("./languages/jupyter-notebook").then((module) => module.jupyterNotebook),
  julia: () => import("./languages/julia").then((module) => module.julia),
  kotlin: () => import("./languages/kotlin").then((module) => module.kotlin),
  lean: () => import("./languages/lean").then((module) => module.lean),
  less: () => import("./languages/less").then((module) => module.less),
  liquid: () => import("./languages/liquid").then((module) => module.liquid),
  lisp: () => import("./languages/lisp").then((module) => module.lisp),
  "llvm-ir": () => import("./languages/llvm-ir").then((module) => module.llvmIr),
  lua: () => import("./languages/lua").then((module) => module.lua),
  luau: () => import("./languages/luau").then((module) => module.luau),
  makefile: () => import("./languages/makefile").then((module) => module.makefile),
  matlab: () => import("./languages/matlab").then((module) => module.matlab),
  markdown: () => import("./languages/markdown").then((module) => module.markdown),
  mdx: () => import("./languages/mdx").then((module) => module.mdx),
  mermaid: () => import("./languages/mermaid").then((module) => module.mermaid),
  meson: () => import("./languages/meson").then((module) => module.meson),
  metal: () => import("./languages/metal").then((module) => module.metal),
  svn: () => import("./languages/svn").then((module) => module.svn),
  nginx: () => import("./languages/nginx").then((module) => module.nginx),
  nim: () => import("./languages/nim").then((module) => module.nim),
  nix: () => import("./languages/nix").then((module) => module.nix),
  ocaml: () => import("./languages/ocaml").then((module) => module.ocaml),
  "objective-c": () => import("./languages/objective-c").then((module) => module.objectiveC),
  pascal: () => import("./languages/pascal").then((module) => module.pascal),
  perl: () => import("./languages/perl").then((module) => module.perl),
  php: () => import("./languages/php").then((module) => module.php),
  plantuml: () => import("./languages/plantuml").then((module) => module.plantuml),
  powershell: () => import("./languages/powershell").then((module) => module.powershell),
  prolog: () => import("./languages/prolog").then((module) => module.prolog),
  protobuf: () => import("./languages/protobuf").then((module) => module.protobuf),
  pug: () => import("./languages/pug").then((module) => module.pug),
  python: () => import("./languages/python").then((module) => module.python),
  qml: () => import("./languages/qml").then((module) => module.qml),
  r: () => import("./languages/r").then((module) => module.r),
  racket: () => import("./languages/racket").then((module) => module.racket),
  razor: () => import("./languages/razor").then((module) => module.razor),
  rego: () => import("./languages/rego").then((module) => module.rego),
  ruby: () => import("./languages/ruby").then((module) => module.ruby),
  rust: () => import("./languages/rust").then((module) => module.rust),
  scala: () => import("./languages/scala").then((module) => module.scala),
  scss: () => import("./languages/scss").then((module) => module.scss),
  solidity: () => import("./languages/solidity").then((module) => module.solidity),
  sql: () => import("./languages/sql").then((module) => module.sql),
  starlark: () => import("./languages/starlark").then((module) => module.starlark),
  svelte: () => import("./languages/svelte").then((module) => module.svelte),
  svg: () => import("./languages/svg").then((module) => module.svg),
  swift: () => import("./languages/swift").then((module) => module.swift),
  tcl: () => import("./languages/tcl").then((module) => module.tcl),
  tex: () => import("./languages/tex").then((module) => module.tex),
  toml: () => import("./languages/toml").then((module) => module.toml),
  twig: () => import("./languages/twig").then((module) => module.twig),
  typescript: () => import("./languages/typescript").then((module) => module.typescript),
  typst: () => import("./languages/typst").then((module) => module.typst),
  verilog: () => import("./languages/verilog").then((module) => module.verilog),
  vhdl: () => import("./languages/vhdl").then((module) => module.vhdl),
  "visual-basic": () => import("./languages/visual-basic").then((module) => module.visualBasic),
  vue: () => import("./languages/vue").then((module) => module.vue),
  webassembly: () => import("./languages/webassembly").then((module) => module.webassembly),
  wgsl: () => import("./languages/wgsl").then((module) => module.wgsl),
  xaml: () => import("./languages/xaml").then((module) => module.xaml),
  xml: () => import("./languages/xml").then((module) => module.xml),
  xquery: () => import("./languages/xquery").then((module) => module.xquery),
  xslt: () => import("./languages/xslt").then((module) => module.xslt),
  yaml: () => import("./languages/yaml").then((module) => module.yaml),
  zig: () => import("./languages/zig").then((module) => module.zig),
  zsh: () => import("./languages/zsh").then((module) => module.zsh),
} as const satisfies Record<string, () => Promise<Language>>;

export type LanguageSlug = keyof typeof languageLoaders;

/** Dynamically imports a language module by slug. */
export const loadLanguage = (slug: string) => languageLoaders[slug as LanguageSlug]?.();
