import type { Language } from "./types";

export interface LanguageIndexEntry {
  slug: string;
  extensions: readonly string[];
}

/** Lightweight slug and extension index used by lazy filename detection. */
export const languageIndex = [
  { slug: "abap", extensions: [".abap"] },
  { slug: "actionscript", extensions: [".as"] },
  { slug: "asp", extensions: [".asp", ".aspx", ".ascx", ".ashx", ".asmx", ".master"] },
  { slug: "astro", extensions: [".astro"] },
  { slug: "assembly", extensions: [".asm", ".s", ".S", ".inc"] },
  {
    slug: "bash",
    extensions: [".sh", ".bash", ".bashrc", ".bash_profile", ".bash_login", ".profile"],
  },
  { slug: "batch", extensions: [".bat", ".cmd"] },
  { slug: "c", extensions: [".c", ".h"] },
  { slug: "cmake", extensions: ["CMakeLists.txt", ".cmake"] },
  { slug: "coffeescript", extensions: [".coffee", ".litcoffee", ".cson"] },
  { slug: "cobol", extensions: [".cob", ".cbl", ".cobol", ".cpy"] },
  { slug: "cpp", extensions: [".cpp", ".cc", ".cxx", ".h", ".hpp", ".hh", ".hxx"] },
  { slug: "csharp", extensions: [".cs", ".csx"] },
  { slug: "crystal", extensions: [".cr"] },
  { slug: "css", extensions: [".css"] },
  { slug: "cuda", extensions: [".cu", ".cuh"] },
  { slug: "dart", extensions: [".dart"] },
  { slug: "dockerfile", extensions: ["Dockerfile", ".dockerfile"] },
  { slug: "elm", extensions: [".elm"] },
  {
    slug: "fortran",
    extensions: [".f", ".for", ".ftn", ".f90", ".f95", ".f03", ".f08", ".f18", ".f23"],
  },
  { slug: "fsharp", extensions: [".fs", ".fsi", ".fsx", ".fsscript"] },
  { slug: "git", extensions: [".git", ".gitignore", ".gitattributes", ".gitmodules", ".gitkeep"] },
  { slug: "go", extensions: [".go"] },
  { slug: "gradle", extensions: [".gradle", ".gradle.kts"] },
  { slug: "graphql", extensions: [".graphql", ".gql", ".graphqls"] },
  { slug: "groovy", extensions: [".groovy", ".gvy", ".gy", ".gsh"] },
  { slug: "html", extensions: [".html", ".htm"] },
  { slug: "ini", extensions: [".ini"] },
  { slug: "java", extensions: [".java"] },
  { slug: "javascript", extensions: [".js", ".mjs", ".cjs", ".jsx"] },
  { slug: "json", extensions: [".json"] },
  { slug: "julia", extensions: [".jl"] },
  { slug: "kotlin", extensions: [".kt", ".kts"] },
  { slug: "less", extensions: [".less"] },
  { slug: "lisp", extensions: [".lisp", ".lsp", ".cl", ".asd"] },
  { slug: "lua", extensions: [".lua", ".rockspec"] },
  { slug: "makefile", extensions: ["Makefile", "makefile", "GNUmakefile", ".mk", ".mak"] },
  { slug: "matlab", extensions: [".m", ".mlx"] },
  { slug: "markdown", extensions: [".md", ".markdown", ".mdown", ".mkd"] },
  { slug: "meson", extensions: ["meson.build", "meson_options.txt", "meson.options", ".wrap"] },
  { slug: "metal", extensions: [".metal"] },
  { slug: "nginx", extensions: ["nginx.conf", ".nginx", ".conf"] },
  { slug: "objective-c", extensions: [".m", ".mm"] },
  { slug: "pascal", extensions: [".pas", ".pp", ".inc", ".lpr", ".dpr", ".dfm"] },
  { slug: "perl", extensions: [".pl", ".pm", ".pod", ".t", ".psgi"] },
  { slug: "php", extensions: [".php", ".phtml", ".php3", ".php4", ".php5", ".phps"] },
  { slug: "powershell", extensions: [".ps1", ".psm1", ".psd1", ".ps1xml"] },
  { slug: "pug", extensions: [".pug", ".jade"] },
  { slug: "python", extensions: [".py", ".pyw"] },
  { slug: "r", extensions: [".r", ".R", ".rmd", ".Rmd", ".qmd", ".Rprofile"] },
  {
    slug: "ruby",
    extensions: [".rb", ".rbw", ".rake", ".gemspec", "Gemfile", "Rakefile", "config.ru"],
  },
  { slug: "rust", extensions: [".rs"] },
  { slug: "scala", extensions: [".scala", ".sc"] },
  { slug: "scss", extensions: [".scss", ".sass"] },
  { slug: "sql", extensions: [".sql"] },
  { slug: "svg", extensions: [".svg", ".svgz"] },
  { slug: "svelte", extensions: [".svelte"] },
  { slug: "swift", extensions: [".swift"] },
  { slug: "toml", extensions: [".toml"] },
  { slug: "typescript", extensions: [".ts", ".tsx", ".mts", ".cts"] },
  { slug: "visual-basic", extensions: [".vb"] },
  { slug: "vue", extensions: [".vue"] },
  { slug: "webassembly", extensions: [".wasm", ".wat"] },
  { slug: "xaml", extensions: [".xaml", ".baml"] },
  { slug: "xml", extensions: [".xml", ".xsd", ".xsl", ".xslt"] },
  { slug: "yaml", extensions: [".yaml", ".yml"] },
  { slug: "zig", extensions: [".zig", ".zon"] },
  {
    slug: "zsh",
    extensions: [".zsh", ".zshrc", ".zshenv", ".zprofile", ".zlogin", ".zlogout", ".zsh-theme"],
  },
] as const satisfies readonly LanguageIndexEntry[];

/** Explicit dynamic import map for every language module. */
export const languageLoaders = {
  abap: () => import("./languages/abap").then((module) => module.abap),
  actionscript: () => import("./languages/actionscript").then((module) => module.actionscript),
  asp: () => import("./languages/asp").then((module) => module.asp),
  assembly: () => import("./languages/assembly").then((module) => module.assembly),
  astro: () => import("./languages/astro").then((module) => module.astro),
  bash: () => import("./languages/bash").then((module) => module.bash),
  batch: () => import("./languages/batch").then((module) => module.batch),
  c: () => import("./languages/c").then((module) => module.c),
  cmake: () => import("./languages/cmake").then((module) => module.cmake),
  cobol: () => import("./languages/cobol").then((module) => module.cobol),
  coffeescript: () => import("./languages/coffeescript").then((module) => module.coffeescript),
  cpp: () => import("./languages/cpp").then((module) => module.cpp),
  csharp: () => import("./languages/csharp").then((module) => module.csharp),
  crystal: () => import("./languages/crystal").then((module) => module.crystal),
  css: () => import("./languages/css").then((module) => module.css),
  cuda: () => import("./languages/cuda").then((module) => module.cuda),
  dart: () => import("./languages/dart").then((module) => module.dart),
  dockerfile: () => import("./languages/dockerfile").then((module) => module.dockerfile),
  elm: () => import("./languages/elm").then((module) => module.elm),
  fortran: () => import("./languages/fortran").then((module) => module.fortran),
  fsharp: () => import("./languages/fsharp").then((module) => module.fsharp),
  git: () => import("./languages/git").then((module) => module.git),
  go: () => import("./languages/go").then((module) => module.go),
  gradle: () => import("./languages/gradle").then((module) => module.gradle),
  graphql: () => import("./languages/graphql").then((module) => module.graphql),
  groovy: () => import("./languages/groovy").then((module) => module.groovy),
  html: () => import("./languages/html").then((module) => module.html),
  ini: () => import("./languages/ini").then((module) => module.ini),
  java: () => import("./languages/java").then((module) => module.java),
  javascript: () => import("./languages/javascript").then((module) => module.javascript),
  json: () => import("./languages/json").then((module) => module.json),
  julia: () => import("./languages/julia").then((module) => module.julia),
  kotlin: () => import("./languages/kotlin").then((module) => module.kotlin),
  less: () => import("./languages/less").then((module) => module.less),
  lisp: () => import("./languages/lisp").then((module) => module.lisp),
  lua: () => import("./languages/lua").then((module) => module.lua),
  makefile: () => import("./languages/makefile").then((module) => module.makefile),
  matlab: () => import("./languages/matlab").then((module) => module.matlab),
  markdown: () => import("./languages/markdown").then((module) => module.markdown),
  meson: () => import("./languages/meson").then((module) => module.meson),
  metal: () => import("./languages/metal").then((module) => module.metal),
  nginx: () => import("./languages/nginx").then((module) => module.nginx),
  "objective-c": () => import("./languages/objective-c").then((module) => module.objectiveC),
  pascal: () => import("./languages/pascal").then((module) => module.pascal),
  perl: () => import("./languages/perl").then((module) => module.perl),
  php: () => import("./languages/php").then((module) => module.php),
  powershell: () => import("./languages/powershell").then((module) => module.powershell),
  pug: () => import("./languages/pug").then((module) => module.pug),
  python: () => import("./languages/python").then((module) => module.python),
  r: () => import("./languages/r").then((module) => module.r),
  ruby: () => import("./languages/ruby").then((module) => module.ruby),
  rust: () => import("./languages/rust").then((module) => module.rust),
  scala: () => import("./languages/scala").then((module) => module.scala),
  scss: () => import("./languages/scss").then((module) => module.scss),
  sql: () => import("./languages/sql").then((module) => module.sql),
  svelte: () => import("./languages/svelte").then((module) => module.svelte),
  svg: () => import("./languages/svg").then((module) => module.svg),
  swift: () => import("./languages/swift").then((module) => module.swift),
  toml: () => import("./languages/toml").then((module) => module.toml),
  typescript: () => import("./languages/typescript").then((module) => module.typescript),
  "visual-basic": () => import("./languages/visual-basic").then((module) => module.visualBasic),
  vue: () => import("./languages/vue").then((module) => module.vue),
  webassembly: () => import("./languages/webassembly").then((module) => module.webassembly),
  xaml: () => import("./languages/xaml").then((module) => module.xaml),
  xml: () => import("./languages/xml").then((module) => module.xml),
  yaml: () => import("./languages/yaml").then((module) => module.yaml),
  zig: () => import("./languages/zig").then((module) => module.zig),
  zsh: () => import("./languages/zsh").then((module) => module.zsh),
} as const satisfies Record<string, () => Promise<Language>>;

export type LanguageSlug = keyof typeof languageLoaders;

/** Dynamically imports a language module by slug. */
export const loadLanguage = (slug: string) => languageLoaders[slug as LanguageSlug]?.();
